name: Build

on:
  push:
    branches: [main]

jobs:
  linux_arm7:
    name: Linux ChromeOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-cros-linux-gnu-gcc
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-cros-linux-gnu-gcc
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: target/debug/gameoflife.exe
